apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-app
  namespace: car-rental
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-rental
  template:
    metadata:
      labels:
        app: car-rental
    spec:
      containers:
      - name: backend
        image: ganesh/car-rental-backend:latest
        ports:
        - containerPort: 5000
      - name: frontend
        image: ganesh/car-rental-frontend:latest
        ports:
        - containerPort: 3000
