apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-rental-ingress
  namespace: car-rental
spec:
  rules:
  - host: car-rental.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: car-rental-service
            port:
              number: 3000
