apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
  namespace: car-rental
spec:
  selector:
    app: car-rental
  ports:
  - name: backend
    port: 5000
    targetPort: 5000
  - name: frontend
    port: 3000
    targetPort: 3000
  type: LoadBalancer
